# Generated by Django 5.0.3 on 2024-04-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='hotelimage',
            field=models.FileField(upload_to='hotel-image'),
        ),
    ]
