# Generated by Django 5.0.3 on 2024-04-28 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation_type',
            fields=[
                ('acctype_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hotels',
            name='acctype',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='todo.accommodation_type'),
            preserve_default=False,
        ),
    ]
