# Generated by Django 5.0.3 on 2024-04-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_hotels_hotelimage_hotelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='hotelimage',
            field=models.ImageField(default=str, upload_to='hotel-images'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HotelImage',
        ),
    ]
