# Generated by Django 5.0.3 on 2024-04-30 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_hotels_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='hotel',
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(upload_to='booking-app-images'),
        ),
        migrations.CreateModel(
            name='Accommodations',
            fields=[
                ('acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('accname', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('totalroom', models.IntegerField()),
                ('roommap', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('rating', models.IntegerField()),
                ('createdAt', models.DateField()),
                ('updatedAt', models.DateField()),
                ('acctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.accommodation_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='accommodations',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='todo.accommodations'),
            preserve_default=False,
        ),
    ]
