# Generated by Django 5.0.3 on 2024-05-02 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_hotelimage_hotel_alter_hotelimage_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelImage',
            new_name='AccommodationImage',
        ),
        migrations.DeleteModel(
            name='Hotels',
        ),
    ]
