# Generated by Django 5.0.3 on 2024-04-20 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_hotels_hotelimage_delete_hotelimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='hotelimage',
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel-images')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='todo.hotels')),
            ],
        ),
    ]
