# Generated by Django 5.0.3 on 2024-05-02 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_rename_hotelimage_accommodationimage_delete_hotels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('roomtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('roomname', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('roomprice', models.IntegerField()),
                ('roomnumber', models.IntegerField()),
                ('roomoccupancy', models.IntegerField()),
                ('createdAt', models.DateField()),
                ('updatedAt', models.DateField()),
                ('accommodations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.accommodations')),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.room_type')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='booking-app-images')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='todo.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='todo.rooms')),
            ],
        ),
    ]
