# Generated by Django 5.0.3 on 2024-04-20 07:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_hotelimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='hotelimage',
            field=cloudinary.models.CloudinaryField(default=str, max_length=255, verbose_name='hotel-images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='hotel-images'),
        ),
    ]
