# Generated by Django 5.0.3 on 2024-05-06 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='joined',
        ),
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='users',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='images',
            field=models.ImageField(default=str, upload_to='booking-app-images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='sex_type',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
