# Generated by Django 5.0.3 on 2024-04-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_hotels_hotelimage_alter_hotelimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='hotelimage',
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(upload_to='hotel-images'),
        ),
    ]
