# Generated by Django 5.0.3 on 2024-04-22 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_remove_hotels_hotelimage_alter_hotelimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotels',
            name='image',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='todo.hotelimage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
