# Generated by Django 5.0.3 on 2024-05-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_users_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodations',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accommodations',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
