# Generated by Django 5.0.3 on 2024-04-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_remove_hotelimage_hotel_hotels_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='id',
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='image_id',
            field=models.AutoField(default=int, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
