# Generated by Django 5.0.3 on 2024-05-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_alter_accommodations_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='images',
            field=models.ImageField(default='https://res.cloudinary.com/dzi8e6scb/image/upload/v1713672680/avatar_spd3di.jpg', upload_to='booking-app-images'),
        ),
    ]
