# Generated by Django 5.0.3 on 2024-04-22 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_remove_hotelimage_id_hotelimage_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='image',
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='hotel',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='todo.hotels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='id',
            field=models.BigAutoField(auto_created=True, default=int, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
