# Generated by Django 5.0.3 on 2024-05-09 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_booking_recomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('utilities_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomUtilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='todo.rooms')),
            ],
        ),
    ]
