# Generated by Django 5.0.3 on 2024-05-13 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_utilities_roomutilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationUtilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('accommodations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='todo.accommodations')),
            ],
        ),
        migrations.DeleteModel(
            name='RoomUtilities',
        ),
    ]
